"""rk_report -- self-contained auxiliary HTML report (plan 4.7, D8).

report --run DIR -> <run_dir>/aux_report.html (no external links/scripts),
                    run.json "aux_report" + "official_reports"

Contents: run conditions (test, corners, life, windows, RelStudio version,
Work_Dir), the per-corner result summary, aging worst devices, DEOS
violations (or top DPM devices), EMIR summary, and where RelStudio's own
official reports are (D8: the official report is RelStudio's; this one is
only an aid).

Python 3.8+, stdlib only.
"""

import html
import os

import rk_common

TOP_N = 20


def esc(v):
    if v is None:
        return ""
    if isinstance(v, float):
        return html.escape("%.4g" % v)
    return html.escape(str(v))


def read_tsv(path, limit=None):
    if not path or not os.path.isfile(path):
        return [], []
    with open(path, "r", encoding="utf-8") as f:
        lines = f.read().splitlines()
    if not lines:
        return [], []
    header = lines[0].split("\t")
    rows = [l.split("\t") for l in lines[1:]]
    return header, rows[:limit] if limit else rows


def table(header, rows, sev_col=None, cls=""):
    out = ['<table class="%s"><thead><tr>' % cls]
    out += ["<th>%s</th>" % esc(h) for h in header]
    out.append("</tr></thead><tbody>")
    for r in rows:
        sev = r[sev_col] if sev_col is not None and sev_col < len(r) else ""
        out.append('<tr class="%s">' % esc(sev))
        out += ["<td>%s</td>" % esc(v) for v in r]
        out.append("</tr>")
    out.append("</tbody></table>")
    return "".join(out)


CSS = """
:root{--bg:#fff;--fg:#1d1d1f;--mut:#6b6b70;--line:#d9d9de;--fail:#fde2e1;--failfg:#9b1c1c;
--warn:#fff4d6;--pass:#e3f6e8;--passfg:#17663a;--head:#f3f3f6}
@media (prefers-color-scheme: dark){:root{--bg:#18181b;--fg:#ececf0;--mut:#a0a0a8;
--line:#3a3a40;--fail:#4a1f1f;--failfg:#ffb4b4;--warn:#4a3d16;--pass:#173a25;--passfg:#a6e9bd;
--head:#232328}}
body{background:var(--bg);color:var(--fg);font:14px/1.45 system-ui,-apple-system,Segoe UI,
Roboto,Helvetica,Arial,sans-serif;margin:0;padding:24px 16px;max-width:1200px;margin:auto}
h1{font-size:22px;margin:0 0 4px}h2{font-size:17px;margin:28px 0 8px;border-bottom:1px solid
var(--line);padding-bottom:4px}.mut{color:var(--mut)}table{border-collapse:collapse;width:100%;
margin:6px 0;font-size:13px;display:block;overflow-x:auto}th,td{border:1px solid var(--line);
padding:4px 8px;text-align:left;white-space:nowrap}th{background:var(--head)}tr.fail td{
background:var(--fail)}tr.warn td{background:var(--warn)}.badge{display:inline-block;
padding:2px 10px;border-radius:10px;font-weight:600}.badge.pass{background:var(--pass);
color:var(--passfg)}.badge.fail{background:var(--fail);color:var(--failfg)}.badge.unk{
background:var(--head)}dl{display:grid;grid-template-columns:max-content 1fr;gap:4px 16px;
margin:0}dt{color:var(--mut)}dd{margin:0;word-break:break-all}code{font-size:12px}
"""


def badge(p):
    if p is True:
        return '<span class="badge pass">PASS</span>'
    if p is False:
        return '<span class="badge fail">FAIL</span>'
    return '<span class="badge unk">?</span>'


def build_html(run, summary, run_dir):
    t = run.get("type")
    st = run.get("settings") or {}
    title = "relkit %s report - %s" % ({"aging": "aging", "deos": "DEOS", "emir": "EMIR"}.get(t, t),
                                       run.get("id"))
    parts = ["<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">",
             "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">",
             "<title>%s</title><style>%s</style></head><body>" % (esc(title), CSS)]
    overall = (summary or {}).get("pass")
    parts.append("<h1>%s %s</h1>" % (esc(title), badge(overall)))
    parts.append('<p class="mut">Auxiliary report generated by relkit. The official report is '
                 "RelStudio's own (listed below).</p>")

    # conditions
    m = run.get("maestro") or {}
    dut = run.get("dut") or {}
    cond = [("Run id", run.get("id")), ("Type", "%s (%s)" % (t, run.get("rs_type"))),
            ("State", run.get("state")), ("Created", run.get("created")),
            ("User", run.get("user")),
            ("Maestro", "%s / %s / %s" % (m.get("lib"), m.get("cell"), m.get("view"))),
            ("Test", run.get("test")),
            ("DUT", "%s -> %s/%s" % (dut.get("inst"), dut.get("lib"), dut.get("cell"))),
            ("IP / Cell / Project", "%s / %s / %s" % (run.get("ip_name"), run.get("cell_name"),
                                                      run.get("project_name"))),
            ("RelStudio", run.get("relstudio_home")),
            ("Work_Dir", run.get("work_dir")),
            ("Netlist", "%s (sha1 %s)" % ((run.get("netlist") or {}).get("path"),
                                          ((run.get("netlist") or {}).get("sha1") or "")[:12]))]
    if t in ("aging", "deos", "emir"):
        cond.append(("Life time", "%s %s" % (st.get("life_time"), st.get("life_time_unit"))))
        cond.append(("Time window", "%s .. %s" % (st.get("start_time"), st.get("stop_time"))))
    if t == "aging":
        cond.append(("Evaluation temperatures", st.get("eval_temperatures") or "corner temperature"))
    if t == "deos":
        cond.append(("Simulation time", st.get("simulation_time")))
        cond.append(("TDDB temperature", st.get("tddb_temperature") or "corner temperature"))
    if t == "emir":
        cond += [("Run type", st.get("run_type")), ("Self-heating", st.get("selfheat")),
                 ("EM temperature", st.get("em_temperature")), ("RC corner", st.get("rc_corner")),
                 ("DSPF", st.get("dspf_file")), ("GDS", st.get("gds_file")),
                 ("Supplies", st.get("supplies")),
                 ("License retries", (run.get("license") or {}).get("retries"))]
    parts.append("<h2>Conditions</h2><dl>")
    for k, v in cond:
        parts.append("<dt>%s</dt><dd>%s</dd>" % (esc(k), esc(v)))
    parts.append("</dl>")
    corners = run.get("corners") or []
    if corners:
        rows = []
        for c in corners:
            secs = ", ".join("%s" % (s.get("section") or "") for s in c.get("sections") or [])
            vs = ", ".join("%s=%s" % kv for kv in sorted((c.get("vars") or {}).items()))
            rows.append([c.get("name"), c.get("temperature"), secs, vs])
        parts.append("<h2>Corners</h2>" + table(["Corner", "Temp", "Sections", "Variables"], rows))

    # results
    parts.append("<h2>Results</h2>")
    if not summary:
        parts.append('<p class="mut">No parsed results (run not finished or collect failed).</p>')
    else:
        h, rows = read_tsv(summary.get("summary_table_path"))
        if h:
            keep = [i for i, x in enumerate(h) if not x.startswith("_")]
            sev = h.index("_sev") if "_sev" in h else None
            disp = [[r[i] if i < len(r) else "" for i in keep] + [r[sev] if sev is not None and sev < len(r) else ""]
                    for r in rows]
            parts.append(table([h[i] for i in keep], disp, sev_col=len(keep)))
        for c in summary.get("corners") or []:
            hh, rr = read_tsv(c.get("table_path"))
            if not hh:
                continue
            sev = hh.index("_sev") if "_sev" in hh else None
            keep = [i for i, x in enumerate(hh) if not x.startswith("_")]
            if t == "deos":
                bad = [r for r in rr if sev is not None and r[sev] == "fail"]
                label = "violations" if bad else "top %d devices by DPM (no violation)" % TOP_N
                sel = bad if bad else rr[:TOP_N]
            elif t == "aging":
                label = "worst %d devices by didsat(HCI+BTI,%%)" % TOP_N
                sel = rr[:TOP_N]
            else:
                sel = [r for r in rr if r[keep[0]] in ("EM", "IR worst")] + \
                      [r for r in rr if r[keep[0]] == "IR"][:10]
                label = "EM violations, IR worst points"
            parts.append("<h3>%s %s &mdash; %s %s</h3>" % (
                esc(c.get("corner")), ("(Stress %s)" % esc(c.get("stress_id"))) if c.get("stress_id") else "",
                esc(label), badge(c.get("pass"))))
            disp = [[r[i] if i < len(r) else "" for i in keep] + [r[sev] if sev is not None else ""]
                    for r in sel]
            parts.append(table([hh[i] for i in keep], disp, sev_col=len(keep)))

    # R1 aged corners (rk_aged: hrmi copies + fresh/aged delta tables from Maestro)
    if run.get("hrmi") or run.get("aged_delta"):
        parts.append("<h2>Aged corners in Maestro (R1)</h2>")
        hr = run.get("hrmi") or {}
        if hr:
            rows = [[sid, v.get("corner"), v.get("include_path")]
                    for sid, v in sorted(hr.items(), key=lambda kv: (len(kv[0]), kv[0]))]
            parts.append(table(["Stress", "Corner", "Aged include"], rows))
        for d in run.get("aged_delta") or []:
            hh, rr = read_tsv(d.get("table_path"))
            if not hh:
                continue
            keep = [i for i, x in enumerate(hh) if not x.startswith("_")]
            sev = hh.index("_sev") if "_sev" in hh else None
            parts.append("<h3>Fresh vs aged &mdash; Maestro history %s</h3>" % esc(d.get("history")))
            parts.append(table([hh[i] for i in keep],
                               [[r[i] if i < len(r) else "" for i in keep] +
                                [r[sev] if sev is not None and sev < len(r) else ""] for r in rr],
                               sev_col=len(keep)))

    # official reports
    parts.append("<h2>RelStudio official reports</h2>")
    reps = run.get("official_reports") or []
    if reps:
        rows = [[r.get("name"), r.get("path"), r.get("pdf") or "", r.get("copy") or ""] for r in reps]
        parts.append(table(["Report", "Original (Work_Dir)", "PDF", "Copy in run record"], rows))
    else:
        parts.append('<p class="mut">None found.</p>')
    parts.append('<p class="mut">relkit run record: <code>%s</code></p>' % esc(run_dir))
    parts.append("</body></html>\n")
    return "".join(parts)


def make_report(run_dir):
    import rk_submit
    run_dir = os.path.abspath(run_dir)
    run = rk_submit.load_run(run_dir)
    if run.get("type_dir") and os.path.isdir(run["type_dir"]):
        try:
            reps = rk_submit.copy_official_reports(run)
            if reps:
                run["official_reports"] = reps
        except OSError:
            pass
    sp = os.path.join(run_dir, "summary.json")
    summary = rk_common.read_json(sp) if os.path.isfile(sp) else None
    path = os.path.join(run_dir, "aux_report.html")
    text = build_html(run, summary, run_dir.replace("\\", "/"))
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    os.replace(tmp, path)
    reps = run.get("official_reports") or []

    def upd(r):
        r["aux_report"] = path.replace("\\", "/")
        r["official_reports"] = reps
    rk_submit.update_run(run_dir, upd)
    return {"html_path": path.replace("\\", "/"), "official_reports": reps}


def _cmd_report(args, ctx):
    return make_report(args.run)


def register(subparsers):
    p = rk_common.add_command(subparsers, "report", _cmd_report,
                              "write aux_report.html for a run",
                              ctx_required=False)
    p.add_argument("--run", required=True, help="run record directory (absolute)")
