#!/usr/bin/env python3
"""vh_package -- Stage D: pack a Stage-C build into a relocatable air-gap bundle.

Takes the Stage-C output dir (the one with manifest.json / run.sh) and produces a
SELF-CONTAINED, RELOCATABLE package that runs on the red zone with no path edits:

  pkg/
    <top>_struct.vams, <leaf>.va, stub_*.vams, tb_*.vams   # all sources, flat
    setup_env.sh        # env-agnostic xrun resolution (ambient on red, else fallback)
    run.sh              # references the sources by RELATIVE name; reads ext_libs.list
    ext_libs.list       # external -v/-y/+incdir libs -- EDIT to red paths
    verify.sh           # preflight (pure-digital wreal smoke) THEN run.sh
    README.txt, manifest_D.json
  <pkg>.tar.gz + <pkg>.tar.gz.sha256

Transfer: dev -> (skill_tools deploy / yellow) -> red work dir; untar; `bash verify.sh`.
The preflight proves pure-digital xrun works on THIS machine before trusting the run.

CLI:  python3 vh_package.py --build <stageC_dir> [--out <dir>] [--name <pkgname>]
"""
import os, sys, json, shutil, argparse, hashlib, tarfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import vh_gen as vg

PREFLIGHT_SMOKE = """`timescale 1s/1fs
module vh_pf_dut(o, i); input i; output o; wreal i, o; assign o = 2.0*i; endmodule
module tb; real d; wreal i, o; assign i = d;
  vh_pf_dut u(o, i);
  initial begin d = 3.0; #1;
    if (o == 6.0) $display("=== PREFLIGHT PASS ==="); else $display("=== PREFLIGHT FAIL o=%g ===", o);
    $finish; end
endmodule
"""

VERIFY_SH = """#!/usr/bin/env bash
# AUTO-GENERATED. Air-gap verification: preflight (pure-digital xrun works here?) then run.
set -uo pipefail
cd "$(dirname "$0")"
. ./setup_env.sh || exit 127

echo "================ PREFLIGHT ================"
echo "[preflight] pure-digital wreal smoke (no spectre needed)..."
rm -rf pf.d
xrun -64bit -ams -timescale 1s/1fs -amsvlog_ext .vams,.va vh_preflight.vams \\
  -top tb -access +rwc -xmlibdirname pf.d -l vh_preflight.log >/dev/null 2>&1
if ! grep -q "=== PREFLIGHT PASS ===" vh_preflight.log; then
  echo "*** PREFLIGHT FAILED: pure-digital xrun is not working on this machine."
  echo "    See vh_preflight.log. Fix the xrun env before trusting any result."
  exit 1
fi
echo "[preflight] OK -- pure-digital xrun works, no spectre license needed."

echo "================ DESIGN RUN ==============="
bash run.sh
rc=$?
exit $rc
"""

README = """verilog_helper -- pure-digital verification package
====================================================
Self-contained bundle for DUT top "%(top)s". Runs under xrun in pure-digital
(wreal) mode -- NO spectre license required.

RUN (on the red zone, in this dir):
    bash verify.sh        # preflight smoke, then the design testbench

verify.sh first proves pure-digital xrun works here, then runs run.sh.
A PASS prints:  === TB PASS  (top=%(top)s) ===   and exits 0.

ENVIRONMENT
  - xrun: used directly if on PATH (red zone). Otherwise set
        export VH_SITE_ENV=/path/to/your_cadence_env.sh
    (a script that puts xrun on PATH) and re-run.
  - External HDL libraries (-v): edit  ext_libs.list  to the paths on THIS machine
    (one per line; plain path => -v <path>, or write  -y /dir  /  +incdir+/dir).
    Or set  export VH_EXT_LIBS="/path/a.v /path/b.v".

FILES
  setup_env.sh   env-agnostic xrun resolution (sourced)
  run.sh         the xrun invocation (relative source refs)
  ext_libs.list  external library paths (EDIT for this machine)
  *.vams / *.va  design sources, stubs, testbench
  manifest_D.json  what this package contains

Generated by vh_package (Stage D). Do not commit into the tool repo -- this is
per-DUT user data.
"""


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def flag_to_lines(ext_flags):
    """Turn ['-v','/a.v','-y','/d','+incdir+/i'] into ext_libs.list lines."""
    lines, i = [], 0
    f = ext_flags or []
    while i < len(f):
        t = f[i]
        if t == "-v" and i + 1 < len(f):
            lines.append(f[i + 1]); i += 2
        elif t == "-y" and i + 1 < len(f):
            lines.append("-y %s" % f[i + 1]); i += 2
        elif t.startswith("+"):
            lines.append(t); i += 1
        else:
            lines.append(t); i += 1
    return lines


def main():
    ap = argparse.ArgumentParser(description="Stage D: relocatable air-gap package")
    ap.add_argument("--build", required=True, help="Stage-C output dir (has manifest.json/run.sh)")
    ap.add_argument("--out", help="where to write the package (default: <build>/../package)")
    ap.add_argument("--name", help="package name (default: <top>_pkg)")
    args = ap.parse_args()

    man_path = os.path.join(args.build, "manifest.json")
    if not os.path.isfile(man_path):
        sys.exit("ERROR: %s not found (point --build at a Stage-C output dir)" % man_path)
    man = json.load(open(man_path))
    top = man["top"]
    name = args.name or ("%s_pkg" % top)
    out_root = args.out or os.path.join(os.path.dirname(os.path.abspath(args.build)), "package")
    pkg = os.path.join(out_root, name)
    if os.path.isdir(pkg):
        shutil.rmtree(pkg)
    os.makedirs(pkg)

    # gather every source the run compiles, flatten by basename
    srcs = [man["top_file"]] + [e["file"] for e in man.get("existing_verilogams", [])]
    stubs = [os.path.join(args.build, e["stub"]) for e in man.get("external_stubbed", [])]
    tb = os.path.join(args.build, man["tb"])
    copied, missing = [], []
    for s in srcs + stubs + [tb]:
        if os.path.isfile(s):
            shutil.copy(s, os.path.join(pkg, os.path.basename(s)))
            copied.append(os.path.basename(s))
        else:
            missing.append(s)
    if missing:
        sys.exit("ERROR: missing source files:\n  " + "\n  ".join(missing))

    src_base = [os.path.basename(s) for s in srcs]
    stub_base = [os.path.basename(s) for s in stubs]
    tb_base = os.path.basename(tb)

    # setup_env.sh, run.sh (relative refs, EXT empty -> driven by ext_libs.list), preflight
    open(os.path.join(pkg, "setup_env.sh"), "w").write(vg.SETUP_ENV)
    runsh = os.path.join(pkg, "run.sh")
    open(runsh, "w").write(vg.gen_runsh(top, src_base, stub_base, tb_base, ext_flags=[],
                                        sim_top=man.get("sim_top", "tb")))
    os.chmod(runsh, 0o755)
    open(os.path.join(pkg, "vh_preflight.vams"), "w").write(PREFLIGHT_SMOKE)
    vsh = os.path.join(pkg, "verify.sh")
    open(vsh, "w").write(VERIFY_SH)
    os.chmod(vsh, 0o755)

    # ext_libs.list seeded from the build's ext flags, with edit hint
    ext_lines = flag_to_lines(man.get("ext_flags", []))
    hdr = ("# External HDL libraries for xrun. EDIT to the paths on THIS machine.\n"
           "# one per line: plain path => -v <path>; or  -y /dir  /  +incdir+/dir\n"
           "# (seeded from where the package was built -- red-zone paths likely differ)\n")
    open(os.path.join(pkg, "ext_libs.list"), "w").write(hdr + "\n".join(ext_lines) + ("\n" if ext_lines else ""))

    open(os.path.join(pkg, "README.txt"), "w").write(README % {"top": top})
    manifest_d = {
        "stage": "D", "top": top, "package": name,
        "sources": src_base, "stubs": stub_base, "tb": tb_base,
        "ext_libs_seed": ext_lines,
        "resolved_externals": [e.get("module") for e in man.get("external_resolved", [])],
        "run": "verify.sh -> run.sh", "preflight": "vh_preflight.vams",
    }
    json.dump(manifest_d, open(os.path.join(pkg, "manifest_D.json"), "w"), indent=2)

    # tarball + sha256
    tar_path = os.path.join(out_root, name + ".tar.gz")
    with tarfile.open(tar_path, "w:gz") as tf:
        tf.add(pkg, arcname=name)
    digest = sha256(tar_path)
    open(tar_path + ".sha256", "w").write("%s  %s\n" % (digest, os.path.basename(tar_path)))

    print("=" * 70)
    print("STAGE D -- air-gap package")
    print("=" * 70)
    print("package dir : %s" % pkg)
    print("contents    : %d sources, %d stubs, tb=%s" % (len(src_base), len(stub_base), tb_base))
    print("ext_libs    : %s" % (ext_lines or "(none -- all externals stubbed)"))
    print("tarball     : %s" % tar_path)
    print("sha256      : %s" % digest)
    print()
    print("On the red zone: untar, then  bash %s/verify.sh" % name)


if __name__ == "__main__":
    main()
